 # Publish all joint states -----------------------------------
  ps_joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500  
  
  # Controllers for singular joint ------------------------------------
  # 
  # Effort Position Controllers ---------------------------------------
  
  # VALUES ARE NOT CORRECT !
  EffortJointInterface_PS_controller:
    type: effort_controllers/JointPositionController
    joint: prismatic_joint
    pid: {p: 800.0, i: 100, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}

  PositionJointInterface_PS_controller:
    type: position_controllers/JointPositionController
    joint: prismatic_joint